name = "ai-snapshotsn"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"
main = ".open-next/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "ai-snapshot-db"
database_id = "bc436940-7205-4e6c-839f-3d16be96728b"
